[bot]
channel = "@chumkassa"
subscribe_guard = true

start = '''
ĞŸÑ€Ğ¸Ğ²ĞµÑ‚, {name} {last_name}
ĞŸĞ¾Ğ¿Ğ¾Ğ»Ğ½ĞµĞ½Ğ¸Ğµ/Ğ’Ñ‹Ğ²Ğ¾Ğ´ ÑÑ€ĞµĞ´ÑÑ‚Ğ² Ğ¸Ğ· 1X!

ğŸ“¥ĞŸĞ¾Ğ¿Ğ¾Ğ»Ğ½ĞµĞ½Ğ¸Ğµ: 0%
ğŸ“¤Ğ’Ñ‹Ğ²Ğ¾Ğ´: 0%
ğŸ‘¨â€ğŸ’»Ğ Ğ°Ğ±Ğ¾Ñ‚Ğ°ĞµĞ¼ 24/7

ğŸ‘¨â€ğŸ’»Ğ¡Ğ»ÑƒĞ¶Ğ±Ğ° Ğ¿Ğ¾Ğ´Ğ´ĞµÑ€Ğ¶ĞºĞ¸: @zero1win
ğŸ’•KĞ°Ğ½Ğ°Ğ» : @chumkassa
ğŸ”Ğ’Ğ°ÑˆĞ¸ Ñ‚Ñ€Ğ°Ğ½Ğ·Ğ°ĞºÑ†Ğ¸Ğ¸ Ğ—Ğ°Ñ‰Ğ¸Ñ‰ĞµĞ½Ñ‹ Ğ¤Ğ¸Ğ½Ğ°Ğ½ÑĞ¾Ğ²Ğ¾Ğ¹ ÑĞ»ÑƒĞ¶Ğ±Ğ¾Ğ¹ 1X!
'''

start_buttons = [
    "ğŸ“¥ĞŸĞĞŸĞĞ›ĞĞ•ĞĞ˜Ğ•", 
    "ğŸ“¤Ğ’Ğ«Ğ’ĞĞ”",
    "ğŸ†Ğ˜Ğ½ÑÑ‚Ñ€ÑƒĞºÑ†Ğ¸Ñ",
    "ğŸ³ï¸â€ğŸŒˆĞŸĞµÑ€ĞµĞ²ĞµÑÑ‚Ğ¸ Ğ½Ğ° ĞºÑ‹Ñ€Ğ³Ñ‹Ğ·ÑĞºĞ¸Ğ¹"
]

replenish_message= '''
Ğ’Ñ‹Ğ±ĞµÑ€Ğ¸Ñ‚Ğµ Ğ½ĞµĞ¾Ğ±Ñ…Ğ¾Ğ´Ğ¸Ğ¼Ñ‹Ğ¹ ÑĞ¿Ğ¾ÑĞ¾Ğ± Ğ´Ğ»Ñ Ğ¿Ğ¾Ğ¿Ğ¾Ğ»Ğ½ĞµĞ½Ğ¸Ñ!
'''
replenish_buttons = [
    'MBANK',
    'OptimaBank',
    'BANKA Ğ¾Ğ³ÑƒÑ€Ñ†Ğ¾Ğ²',
    'Ebank',
]

flood_message = 'ĞĞµ Ñ‚Ğ°Ğº Ğ±Ñ‹ÑÑ‚Ñ€Ğ¾!' 

handle_xid = 'Enter your xbet ID !' 
invalid_xid = 'Sorry invalid xbet id , please recheck your id!' 

handle_price = 'Enter price between 3000 and 10000!' 
invalid_price = 'Invalid price , enter between 3000 and 10000 !' 

handle_xid = 'Handle xid!' 
invalid_xid = 'Invalid xid!' 
check_photo = "Check photo please "
chosen_method = "Ğ’Ñ‹Ğ±Ñ€Ğ°Ğ½ Ğ¼ĞµÑ‚Ğ¾Ğ´ Ğ¾Ğ¿Ğ»Ğ°Ñ‚Ñ‹: {method} \n Ğ’Ğ²ĞµĞ´Ğ¸Ñ‚Ğµ Ğ¤Ğ˜Ğ {method} "
